PACKAGE_NAME="i2c-imc-skylake"
PACKAGE_VERSION="1.0"

BUILT_MODULE_NAME[0]="i2c-imc-skylake"
DEST_MODULE_LOCATION[0]="/updates"

MAKE[0]="make KVER=${kernelver}"
CLEAN="make clean KVER=${kernelver}"

AUTOINSTALL="yes"
